[package]
name = "timer"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13", features=["tokio"]}
chrono = "0.4"
notify-rust = "4"
preferences = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
